language: node_js
node_js:
  - 12
cache:
  yarn: true
install:
  - yarn --frozen-lockfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - yarn test:cov
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
